version: '3.7'

services:

  web:
    build: 
      context: web
    restart: always
    environment:
      PYTHONUNBUFFERED: 1
      MONGODB_USERNAME: changeme
      MONGODB_PASSWORD: changeme
      MONGODB_HOST: db
      MONGODB_PORT: 27017
      TZ: Europe/Rome
    ports:
      - 80:5000
    depends_on:
      - db

  updater:
    build: 
      context: updater
    restart: always
    environment:
      PYTHONUNBUFFERED: 1
      MONGODB_USERNAME: changeme
      MONGODB_PASSWORD: changeme
      MONGODB_HOST: db
      MONGODB_PORT: 27017
      WEB_HOST: web
      WEB_PORT: 5000
      TZ: Europe/Rome
    depends_on:
      - db
      - web

  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: changeme
      MONGO_INITDB_ROOT_PASSWORD: changeme
      TZ: Europe/Rome
    volumes:
      - ./docker_db:/data/db